name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: STScript-2020/cc21-artifact/stscript-cc21-artifact
        tags: latest
        cache_froms: docker.pkg.github.com/STScript-2020/cc21-artifact/stscript-cc21-artifact
